from schemas.ai_analysis import AIAnalysisResult

class IncidentExplainer:
    def format_explanation(self, analysis: AIAnalysisResult) -> str:
        """
        Formats the plain-English explanation generated by the AI for the UI.
        """
        return f"AI Diagnosis: {analysis.explanation}"
